config/routes.rb
Rails.application.routes.draw do
   root "pages#home"
    get 'pages/home', to: 'pages#home'
   
   resources :recipes do
    resources :comments, only: [:create]
    member do 
    post 'like'
  end
end
   
   get '/signup', to: 'users#new'
   resources :users, except: [:new]
   
   get '/login', to: 'sessions#new'
   post '/login', to: "sessions#create"
   delete '/logout', to: "sessions#destroy"
   
   resources :ingredients, except: [:destroy]
   
   mount ActionCable.server => '/cable'
   get '/chat', to: 'chatrooms#show'
   
   resources :messages, only: [:create]
   
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :name, presence: true
  validates :description, presence: true, length: {minimum: 5, maximum: 5000}
  default_scope -> {order(updated_at: :desc)}
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  mount_uploader :image, ImageUploader
  
  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size    
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :like]
  before_action :require_user, except: [:index, :show, :like]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_user_like, only: [:like]
  
  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def show
    @comment = Comment.new
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      flash[:success] = "Mmmmmm! Your juicy juice was created successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end
  
  def edit

  end
  
  def update
      if @recipe.update(recipe_params)
      flash[:success] = "Recipe was updated successfully!"
      redirect_to recipe_path(@recipe)
      else
        render 'edit'
      end
  end
  
  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe deleted successfully"
    redirect_to recipes_path
  end
  
  def like
    like = Like.create(like: params[:like], user: current_user, recipe: @recipe)
      if like.valid?
        flash[:success] = "Your selection was succesful"
        redirect_back(fallback_location: root_path)
      else
        flash[:danger] = "You can only like/dislike a recipe once"
        redirect_back(fallback_location: root_path)
      end
  end

private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, :image, ingredient_ids: [])
  end
  
  def require_same_user
    if current_user != @recipe.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own recipes"
      redirect_to recipes_path
    end  
  end
  
  def require_user_like
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_back(fallback_location: root_path)
    end
  end
end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", multipart: true, role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", 
              autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :description %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :description, rows: 10, class: "form-control", 
                                    placeholder: "Enter steps to create recipe" %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class = "col-md-offset-2 col-md-8">
            <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :image, "Add Image" %>
        </div>
        <div class="col-md-8">
          <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-warning btn-lg btn-xlarge" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="user_info center">
        <%= gravatar_for(recipe.user, size: 120) %>
      </section>
    </div>
    <div class="col-md-8 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= truncate(recipe.description, length: 150) %></p>
      <% if recipe.ingredients.any? %>
        <p>Ingredients: <%= render recipe.ingredients %></p>
      <% end %>
      <p>
        <span class="quiet"><small>Created 
        <%= time_ago_in_words(recipe.created_at) %> ago by <%= recipe.user.username.capitalize %>
                        | <%= pluralize(recipe.comments.count, 'Comment') %></small></span>
      </p>
      <% if logged_in? && (current_user == recipe.user || current_user.admin?) %>
        <div class="recipe-actions">
          <%= link_to "Edit this recipe", 
                      edit_recipe_path(recipe), 
                              class: "btn btn-xs btn-warning" %>
          <%= link_to "Delete this recipe", recipe_path(recipe), 
                                  method: :delete,
      data: { confirm: "Are you sure you want to delete this recipe?" },
                                  class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>
      
       <div class="row">
        <div class="pull-right liking">
          <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-up"></i> 
          <% end %> <%= recipe.thumbs_up_total %> || 
          <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-down"></i>
          <% end %> <%= recipe.thumbs_down_total %>
        </div>
      </div>
    </div>
    <div class="col-md-2">
      <%= image_tag(recipe.image.url, size: "250x200") if recipe.image? %>
    </div>
  </div>
<% end %>
    

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "edit an existing recipe" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "Listing All Juice Recipes" %>

<div align="center">
  <%= will_paginate %>
</div>
<p class="center">Click the recipe to view, ask questions and leave comments!</p>
<%= render 'recipe', obj: @recipes %>

<div align="center">
  <%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "create a new juice recipe" %>

<p class = "center">Feel free to add ingredients not present by clicking the ingredients tab, scroll to the bottom, and select "New Ingredient".</p>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="well col-md-8 col-md-offset-2">
  <div align="center">
    <%= image_tag @recipe.image.url if @recipe.image? %>
  </div>
  <h4 class="center description"><strong>Recipe: </strong></h4>
  <hr />
  <%= simple_format(@recipe.description) %>
  <hr />
  <% if @recipe.ingredients.any? %>
    <p>Ingredients: <%= render @recipe.ingredients %></p>
  <% end %>
 
  <div class="pull-right">
    <p class="center">
      <em>Created by:</em>
    </p>
    <p class="center">
      <%= link_to gravatar_for(@recipe.user), user_path(@recipe.user) %>
    </p>
    <p class="center">
      <small><%= @recipe.user.username.capitalize %></small>
      <div class="pull-right"><%= time_ago_in_words(@recipe.created_at) %> ago</div>
    </p>
  </div>
  <div class="recipe-actions">
    <% if logged_in? && (current_user == @recipe.user || current_user.admin?) %>
      <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: "btn btn-xs btn-warning" %>
      <%= link_to "Delete this recipe", recipe_path(@recipe), method: :delete,
                                        data: { confirm: "Are you sure you want to delete this recipe?" },
                                        class: "btn btn-xs btn-danger" %>
    <% end %>                                  
    <%= link_to "Return to recipes listing", recipes_path, class: "btn btn-xs btn-warning" %>
  </div>
</div>

<div class="row">
  <div class="row col-md-8 col-md-offset-2">
    <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
      <i class="glyphicon glyphicon-thumbs-up"></i> 
    <% end %> <%= @recipe.thumbs_up_total %> || 
    <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
      <i class="glyphicon glyphicon-thumbs-down"></i>
    <% end %> <%= @recipe.thumbs_down_total %>
  </div>
</div>
  <% if logged_in? %>
     <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h3>Comments: </h3>
          <hr />
      <%= form_for([@recipe, @comment], remote: true, :html => {class: "form-horizontal", 
                                                role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :description, "Comment" %>
          </div>
          <div class="col-md-8">
            <%= f.text_area :description, rows: 8, class: "form-control", 
                                      placeholder: "Enter Comment Here" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.submit "Submit Comment", 
                              class: "btn btn-warning btn-lg" %>
          </div>
        </div>
      <% end %>
      <hr />
    </div>
  </div>
  <% end %>
  
  <% if @recipe.comments != 0 %>
    <div class= "row">
      <div class="col-md-8 col-md-offset-2">
        <h3>Prior Comments: </h3>
          <div id="messages">
            <%= render partial: 'comments/comments', object: @comments %>
          </div>
        </div>
      </div>
  <% else %>
    <div class= "row">
      <div class="col-md-8 col-md-offset-2">
        <h3>No comments yet!</h3>
      </div>
    </div>
<% end %>    